#! /usr/bin/ruby


input = File.read("data/in.txt")
grid = []
input.split("\n").each_with_index do |line, y|
  grid[y] = []
  line.strip.chars.each_with_index do |char, x|
    grid[y][x] = char
  end
end

def print_grid(grid)
  grid.each do |line|
    puts line.join('')
  end
end

# print_grid(grid)

def surrounding_symbol(grid, x, y, line_length, non_symbols)
  # left
  return true if(x > 0 && !non_symbols.include?(grid[y][x-1]))
  # right
  return true if(x < (line_length-1) && !non_symbols.include?(grid[y][x+1]))
  # above
  return true if(y > 0 && !non_symbols.include?(grid[y-1][x]))
  # below
  return true if(y < (grid.length-1) && !non_symbols.include?(grid[y+1][x]))
  # left above
  return true if(x > 0 && y > 0 && !non_symbols.include?(grid[y-1][x-1]))
  # right above
  return true if(x < (line_length-1) && y > 0 && !non_symbols.include?(grid[y-1][x+1]))
  # left below
  return true if(x > 0 && y < (grid.length-1) && !non_symbols.include?(grid[y+1][x-1]))
  # right below
  return true if(x < (line_length-1) && y < (grid.length-1) && !non_symbols.include?(grid[y+1][x+1]))
  false
end

serial_numbers = []
line_length = grid[0].length
non_symbols = ['.', '0', '1', '2', '3', '4', '5', '6', '7', '8', '9']
grid.each_with_index do |line, y|
  adjacent_symbol = false
  current_nb = nil
  line.each_with_index do |char, x|
    char_nb = Integer char rescue nil

    if char_nb
      # we continue a number
      if current_nb
        current_nb = current_nb * 10 + char_nb
      else
        current_nb = char_nb
      end
      adjacent_symbol ||= surrounding_symbol(grid, x, y, line_length, non_symbols)

      if x == (line_length-1)
        # we ended a number
        if adjacent_symbol
          serial_numbers << current_nb
          # p "added serial EOL: #{current_nb} at #{x},#{y}"
        end
      end
    else
      if current_nb
        # we ended a number
        if adjacent_symbol
          serial_numbers << current_nb
          # p "added serial: #{current_nb} at #{x},#{y}"
        end
      end
      adjacent_symbol = false
      current_nb = nil
    end
  end
end

puts "Answer Part A: #{serial_numbers.sum}"