#!/usr/bin/env ruby

require '../cmd_line_parser'

END {
  run :part1, :part2
}

def part1(input_path)
  puts "Part 1 for file: #{input_path}"
  input = File.read(input_path)
  res = input.split("\n")
             .map { |line|
               numbers = line.chars
                             .map { |c| Integer c rescue nil }
                             .reject(&:nil?)
               numbers[0] * 10 + numbers[-1]
             }.sum
  puts "Answer Part 1: #{res}"
end

def part2(input_path)
  puts "Part 2 for file: #{input_path}"
  input = File.read(input_path)
  res = input.split("\n")
             .map { |line|
               first_nb, last_nb = look_at line
               first_nb * 10 + last_nb
             }.sum
  puts "Answer Part 2: #{res}"
end

def look_at(line)
  tokens = {'one' => 1,
            'two' => 2,
            'three' => 3,
            'four' => 4,
            'five' => 5,
            'six' => 6,
            'seven' => 7,
            'eight' => 8,
            'nine' => 9,
            '1' => 1,
            '2' => 2,
            '3' => 3,
            '4' => 4,
            '5' => 5,
            '6' => 6,
            '7' => 7,
            '8' => 8,
            '9' => 9,
  }
  token_forward_indices = tokens.map { |token|
    line.include?(token[0]) ? [line.index(token[0]), token[1]] : nil
  }
  # puts "line: #{line} token_forward_indices #{token_forward_indices}"
  numbers_sorted_by_index = token_forward_indices
                              .reject(&:nil?)
                              .sort_by { |a| a[0] }
                              .map { |a| a[1] }
  first_number = numbers_sorted_by_index[0]

  token_backward_indices = tokens.map { |token|
    line.include?(token[0]) ? [line.rindex(token[0]), token[1]] : nil
  }
  # puts "line: #{line} token_backward_indices #{token_backward_indices}"
  numbers_sorted_by_index_from_end = token_backward_indices
                                       .reject(&:nil?)
                                       .sort_by { |a| -a[0] }
                                       .map { |a| a[1] }
  last_number = numbers_sorted_by_index_from_end[0]
  [first_number, last_number]
end